import os

file_path = 'C:/Users/shino/Desktop/Project/dashboard/app.py'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Add the Demonstration Mode Toggle to the Sidebar
sidebar_controls = """# Stream slider
min_t = 11
max_t = len(test_df) - 1
t_idx = st.sidebar.slider("Chronological Time Step (Test Stream)", min_value=min_t, max_value=max_t, value=500, step=1)

# Add explicit Demonstration Mode toggle
st.sidebar.markdown("---")
demo_mode = st.sidebar.checkbox("🧪 Enable Demonstration Mode (Oracle)", value=False, help="Injects synthetic probabilities to demonstrate TPPI optimization during attacks. DO NOT use for model evaluation.")

# Map physical time to trust pipeline index"""

content = content.replace("""# Stream slider
min_t = 11
max_t = len(test_df) - 1
t_idx = st.sidebar.slider("Chronological Time Step (Test Stream)", min_value=min_t, max_value=max_t, value=500, step=1)

# Map physical time to trust pipeline index""", sidebar_controls)

# Update the Real Trust Pipeline block to respect the toggle
real_trust_logic = """# ================= REAL TRUST PIPELINE =================
# We load the exact pre-calculated metrics from the frozen Trust Pipeline
attack_prob = trust_row['p_attack']
confidence = trust_row['C']
u_norm = trust_row['U_norm']
ecp = trust_row['ECP']
ts = trust_row['Trust_Score']"""

hybrid_logic = """# ================= REAL TRUST PIPELINE =================
# We load the exact pre-calculated metrics from the frozen Trust Pipeline
attack_prob = trust_row['p_attack']
confidence = trust_row['C']
u_norm = trust_row['U_norm']
ecp = trust_row['ECP']
ts = trust_row['Trust_Score']

# If Demonstration Mode is ON, we use an Oracle to force the dashboard to react
if demo_mode and true_label == 1:
    import numpy as np
    np.random.seed(t_idx)
    attack_prob = np.clip(np.random.normal(0.85, 0.1), 0.55, 0.99)
    # Recalculate TS for the demonstration
    confidence = max(attack_prob, 1 - attack_prob)
    ts = confidence * (1 - u_norm) * ecp
    st.warning("⚠️ **Demonstration Mode Active:** Threat Probability is synthetically generated by an Oracle.")"""

content = content.replace(real_trust_logic, hybrid_logic)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
print("Dashboard Mode Split patched successfully!")
