import os
import pandas as pd
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

file_path = 'C:/Users/shino/Desktop/Project/dashboard/app.py'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Update the warning message
old_warning = 'st.warning("⚠️ **Demonstration Mode Active:** Threat Probability is synthetically generated by an Oracle.")'
new_warning = 'st.warning("⚠️ **DEMONSTRATION MODE — NOT MODEL EVALUATION**\\n\\nAttack probability is synthetically generated using the ground-truth attack state to demonstrate downstream Trust → Risk → TDCRI → TPPI behavior. Metrics shown here must not be reported as IDS performance.")'
content = content.replace(old_warning, new_warning)

# 2. Add permanent evaluation metrics section at the bottom of the dashboard
evaluation_section = """
# ================= GLOBAL EVALUATION METRICS =================
st.write("---")
st.subheader("📈 Evaluation Metrics — Frozen Real Model Results")
st.markdown("These metrics represent the genuine, independent performance of the PyTorch GNN-GRU on the test set (2,078 hours). They are immutable and uninfluenced by Demonstration Mode.")

# Calculate global metrics natively from the loaded trust_df (which is uncorrupted by demo_mode)
pred_global = (trust_df['p_attack'] > 0.5).astype(int)
tn_g, fp_g, fn_g, tp_g = __import__('sklearn').metrics.confusion_matrix(trust_df['true_label'], pred_global).ravel()
prec_g = __import__('sklearn').metrics.precision_score(trust_df['true_label'], pred_global, zero_division=0)
rec_g = __import__('sklearn').metrics.recall_score(trust_df['true_label'], pred_global, zero_division=0)
f1_g = __import__('sklearn').metrics.f1_score(trust_df['true_label'], pred_global, zero_division=0)

m_col1, m_col2, m_col3, m_col4 = st.columns(4)
m_col1.metric("True Positives (TP)", tp_g)
m_col2.metric("False Positives (FP)", fp_g)
m_col3.metric("False Negatives (FN)", fn_g)
m_col4.metric("True Negatives (TN)", tn_g)

m_col5, m_col6, m_col7, m_col8 = st.columns(4)
m_col5.metric("Precision", f"{prec_g*100:.2f}%")
m_col6.metric("Recall", f"{rec_g*100:.2f}%")
m_col7.metric("F1 Score", f"{f1_g*100:.2f}%")
m_col8.metric("Accuracy", f"{(tp_g+tn_g)/len(trust_df)*100:.2f}%")
"""

# Append the evaluation section to the end of the file
if "GLOBAL EVALUATION METRICS" not in content:
    content += "\n" + evaluation_section

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
print("Dashboard updated with exact academic warning and permanent evaluation metrics!")
